name: flutter_flashcards
description: A new Flutter flashcards Application.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1+2
  path_provider: ^1.6.24
  cupertino_icons: ^1.0.0

dev_dependencies:
  bloc_test: ^7.1.0
  pedantic: ^1.9.2
  dartz: ^0.9.2
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  mockito: ^4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf